### ISSUE TITLE
RequestControlAction wrong fields

### ISSUE THREAD

**Issue by aggelosgkiokas** [trompamusic/ce-api#128]
In the RequestControlAction mutation the property values are not consistent with the ones defined in the ControlAction. I have found two issues (I refer to the example of [ce-poc-algorithm](https://github.com/trompamusic/ce-poc-algorithm) ) :

a) Although we link to the ControlAction three objects two types, one Property and two PropertyValueSpecification, the RequestControlAction mutation returns a list of object that contain three items of the same type (PropertyValue)

b) Some fields of these object are wrong
1. For the PropertyValueSpecification objects (that are returned as PropertyValue objects) the field **title** contains the **name**
2. For the Property objects (that are returned as PropertyValue objects) the field **name** contains the **title**

These errors are not evident in the cepoc-algorithm example, because the titles and names are the same in some cases.

**Comment by alastair** [comment]
According to the CE API Manual, section 3.2.4, it's correct that PropertyValue is used for the concrete values linked to the ControlAction on the `object` relation for both PropertyValueSpecification and Property. However, the image shown in this section indicated that there should also be a derivedFrom relationship from this PropertyValue which points to the Property or PropertyValueSpecification that was used as a template. I agree that we should add this.

For PropertyValues that are created from a Property (item in the CE) I see that [both `title` and `name` are set to the `title` of the Property](https://github.com/trompamusic/ce-api/blob/ab0e72eab95f055a6caf46dd03ccc648e265f49d/src/commands/RequestControlActionCommand.js#L229-L230), so this Property:
```
    "Property": [
      {
        "identifier": "2c796031-a303-460a-849d-0be95fb96b03",
        "name": "targetFile",
        "title": "MusicXML File"
        "rangeIncludes": [
          "DigitalDocument"
        ]
      }
    ]
```
becomes this PropertyValue:
```
{
            "title": "MusicXML File",
            "name": "MusicXML File",
            "value": null,
            "nodeValue": {
              "title": "Vivaldi, Concerto no. 4 in F minor „Winter”",
              "source": "https://www.verovio.org/examples/musicxml/Vivaldi_Concerto_No.4_in_F_Minor_Winter.xml",
              "__typename": "DigitalDocument"
            }
```

I agree that we should change `PropertyValue.name` to value of `Property.name`. This way we can iterate through the PropertyValues and treat title as a "user visible" value and name as a "machine readable" value. I see that [the sample algorithm does something similar](https://github.com/trompamusic/ce-poc-algorithm/blob/1509d3add3c5ec33f9541618ba9fad9c6266c997/algorithm/src/index.js#L352-L353).

For PropertyValues that are created from PropertyValueSpecifications (user-provided input), I see that `title` is set to the `title` of the input, and `name` is set to `valueName`. that is, for the following PropertyValueSpecification:
```    "PropertyValueSpecification": [
      {
        "identifier": "f145799e-9612-43cb-9164-ac2d9ea2f460",
        "name": "Result name (name-field)",
        "title": "Result name (title-field)",
        "valueName": "resultName"
      }
```
the resulting PropertyValue is
```
          {
            "title": "Result name (title-field)",
            "name": "resultName",
            "value": "Dedham MEI",
            "valueReference": "String"
          }
```
so this one looks correct to me. We recently made `name` optional in all of these objects, after the demo code was written. I think because of this we can propose that PropertyValueSpecification.name is removed from the sample code. This means that we will have title -> title and valueName -> name. If this is different to the results that you get, please post some examples of how to reproduce the issue.

**Comment by ChristiaanScheermeijer** [comment]
> However, the image shown in this section indicated that there should also be a derivedFrom relationship from this PropertyValue which points to the Property or PropertyValueSpecification that was used as a template. I agree that we should add this.

As discussed, we should add this in the `RequestControlAction` mutation.
