### ISSUE TITLE
How to query all scores that have audios

### ISSUE THREAD

**Issue by hector** [trompamusic/ce-api#132]
I need to perform the following query:
- Return `MusicComposition`s
- Return the url of the their score
- Return the url of all their associated audios
- Filter to only return those `MusicComposition`s that have a score url
- Filter to only return those `MusicComposition`s that have associated audios with creator = "https://www.voiceful.io/"

This is my idea of how this could look like:
```graphql
query {
  MusicComposition(first: 50, filter: {audio: {creator_contains: "https://www.voiceful.io/"}, workExample: {contentUrl_not: null}}) {
    identifier
    title
    audio {
      identifier
      contentUrl
  	}
    workExample {
      ... on MediaObject {
        identifier
        contentUrl
      }
    }
  }
}
```

Obviously this doesn't work.
Discussing with @alastair we found this issue might need to be merged before https://github.com/trompamusic/ce-api/pull/122

**Comment by alastair** [comment]
To add some more detail to this, we found that a query such as this:

> `MusicComposition(filter:{workExample:{contentUrl_not:null}})`

Returns an error:

> "message": "Field \"contentUrl_not\" is not defined by type _CreativeWorkInterfaceFilter. Did you mean character_not, citation_not, funder_not, genre_not, or mainEntity_not?",

The issue is that workExample is a relation to CreativeWorkInterface, but contentUrl is a field on MediaObject and doesn't exist on CreativeWork, so the graphql bindings are unable to generate the expected filter methods.

I had a discussion with @musicog about this. We think that an acceptable solution would be to add specific fields for `workExampleMediaObject` which directly links to a MediaObject. In order to do this we would have to determine all of the targets of the `workExample` relationship and add an item for each of them to the MusicComposition schema definition.
We should also do this for any other relations that we use that are made to Interfaces. I will revise our documentation to make a list.

**Comment by hector** [comment]
For documentation purposes, now this can be done:

```graphql
query {
  MusicComposition(filter:{workExampleMediaObject_some:{contributor:"https://www.voiceful.io/"}}) {
    identifier
    title
    workExampleMediaObject {
      identifier
      contributor
      contentUrl
    }
  }
}
```
