### ISSUE TITLE
Include subscription service for new items added to the CE

### ISSUE THREAD

**Issue by alastair** [trompamusic/ce-api#35]
Some algorithms that we expect to run within the CE will be run by a partner on all documents that exist in the CE.
As an example, MTG might want to run MFCC calculations on all audio files added to the CE, regardless of who adds these documents.

We are proposing to add a subscription endpoint to receive notifications each time a DigitalDocument is added to the CE. 
We're not sure if the subscription should specify possible filters (e.g. mimetype of "audio/"), or if all subscribed clients should receive all documents and perform filtering locally.

**Comment by ChristiaanScheermeijer** [comment]
> We are proposing to add a subscription endpoint to receive notifications each time a DigitalDocument is added to the CE.

We will start working on this feature very soon. We've talked about two possible solutions:

1) Add a single subscription where you can limit the notifications to a few (or single) types. E.g. 

```
subscription AddMutation(onTypes: [DigitalDocument]) {
  ... on DigitalDocument {
    identifier
    title
  }
}
```

2) Add a subscription query for every type in the CE.  Given this could take quite some time to implement per type, for which types do you really want to receive mutations? I will make sure the following types are at least included;

- AudioObject
- CreativeWork
- DigitalDocument
- ImageObject
- MusicComposition
- MusicRecording
- Person
- VideoObject

> We're not sure if the subscription should specify possible filters (e.g. mimetype of "audio/"), or if all subscribed clients should receive all documents and perform filtering locally.

This will depend on which solution will be implemented. If we would pick the 1st solution, custom filters are difficult because we don't know which type if going to be returned. As opposed to the 2nd solution, we can make really specific filters because we know all properties.

```
subscription {
  DigitalDocumentAddMutation(format: "text/html") {
    identifier
    title
  }
}
```

**Comment by musicog** [comment]
From a discussion with @alastair today pertaining to scores (as PDFs and as MEI and MusicXML encodings) I suspect option 2 will be required (sorry!)

Please could you ensure that `MediaObject` is included, and that a filter based on `encodingFormat` is possible.

**Comment by alastair** [comment]
From a pragmatic view, I don't think the CE is going to be getting items added to it at a scale which requires server-side filtering. I see server-side filtering being required if we were receiving thousands of items per hour, which from our discussions so far seems like will not happen.
If it is easier to do 1., then I recommend that we use this process, and then in the future if we see a clear requirement to do additional filtering for a specific usecase, add it for only the data types/filter types for which we need for that usecase.

**Comment by ChristiaanScheermeijer** [comment]
Ok, based on the feedback we will try implementing the first solution and we will also add a separate subscription for MediaObjects with an `encodingFormat` filter, agree?

**Comment by musicog** [comment]
Sounds sensible to me

**Comment by baukef** [comment]
When a new object is susceptible of annotations of type T, the corresponding algorithms must provide their annotations and store them (Julian D4.1)
