### ISSUE TITLE
Requirements for score annotation / MEI improvement

### ISSUE THREAD

**Issue by musicog** [trompamusic/ce-api#43]
This ticket records observations from a discussion between myself and @alastair around score annotation and crowd-based MEI improvement. No direct action required as yet, though there are implications for the use cases and for the multimodal component.

1. Repertoires for use cases that require score annotations **must** be available in MEI format, as the semantic hierarchy and addressability provided by MEI is required in order for Web Annotations to be made. 

This has the implication that scores in other encoding formats (e.g. MusicXML encodings) **must** be converted to **and stored** (e.g. on GitHub) as MEI, and the annotations **must** be made against the MEI encodings. While Verovio is able to convert MusicXML to MEI "on-the-fly" in browser memory, thus appearing to render MusicXML, any annotations created on such on-the-fly renderings would cease to be meaningful as soon as the browser session ends since the identifiers in the converted-MEI would be different on re-rendering. 

2. MusicXML to MEI conversion is imperfect; while we (particularly @wergo) have been working to improve Verovio in this respect, 100% perfect conversion is out of reach. Thus, any use case that converts MusicXML to MEI **must** support (crowd-sourced) MEI correction / improvement.

3. Any MEI intended for crowd correction **must** be tied to a PDF, to act as a reference / ground-truth during the correction process. 

Chaining these three points together, it becomes clear that **any use case wishing to display score annotations must *EITHER* fully "buy-in" to MEI crowd-correction, including storing MEI encodings of scores, and interlinking them with PDF; 

*OR*, commit to creating "perfect" (i.e., fit-for-purpose) MEI encodings through a different mechanism, e.g. through manual encoding. This applies e.g. where a scholarly user might be preparing a new digital edition that has no corresponding physical manifestation (i.e., there is no PDF as there is nothing to scan).

**Comment by alastair** [comment]
This has some effect on the model that we use to store items in the CE.
Currently we have Composers (people), MusicalWorks (works), and DigitalDocuments (files that represent the works). @musicog has suggested that instead of DigitalDocument, we use MediaObject, which has additional fields that allow us to specify more concrete data about the encoding.
In the case of scores, it seems likely that we'll have a MediaObject representing a PDF, and a MediaObject representing a digital transcription of that PDF (and a relationship between them indicating this). In the case that we convert a mxml to mei, we will probably have 2 MediaObjects for the scores.
We may also have a score MediaObject which is not related to a pdf (e.g. a new "digital-first" transcription/edition). 
We need to ensure that with the CE api we can retrieve all MediaObjects of a specific type which are related to a specific composition.
We haven't thought much about how mediaobjects of different types will be represented (images? of people?, recordings). This will have to be clarified in the near future as we add more content to the CE.
