### ISSUE TITLE
Decide where to store the result of algorithms

### ISSUE THREAD

**Issue by david-linssen** [trompamusic/ce-api#70]
submitted by UPF, relevant for Enthusiasts, Choirs, Instrument Players

**Comment by baukef** [comment]
First proposal is to store this in the AWS S3 Trompa account managed by Videodock.

**Comment by baukef** [comment]
Please send your request for a AWS 'key_id' and 'secret' to the Videodock support e-mail address.

**Comment by musicog** [comment]
TROMPA applications have application-level accounts in the CE.
TROMPA applications create objects in S3 buckets for authenticated users.
If the uploaded content is "private", the application sets permissions in the S3 bucket so that only *it* (the application) can read the item.

Users access their objects in the S3 buckets *through* the TROMPA application.
A different user attempting access through the application will fail.
A separate application will fail. 
Accessing them directly in the S3 results in a 403 response. 

The application can make the item in the S3 bucket public (on user request), in which case it becomes world readable.
@alastair @asarasua

**Comment by baukef** [comment]
@musicog Should we really refer to this as CE? 
Just to be sure: we all agree that this data can't contain personal data (and/or personally identifiable information), right? 

I also assumed that this data is public data and temporary. The idea is to contribute to existing (third-party) repositories for long-term valuable data as much as possible. 

I would like to propose that we auto-delete these S3-stored results of algorithms after two weeks or so. If I understood well, the idea - as Alastair proposed- is that we should be able to reproduce algorithmic results anyway. 

As discussed, private (user data) should be stored in solid pods hosted by UPF. @david-linssen

**Comment by baukef** [comment]
FYI Neo4j now also supports private data. 

"With Neo4j 4.0, developers and administrators now have more control over access to data for security and privacy purposes. These granular security controls ensure that only the appropriate users have access to sensitive data, opening up potential new graph use cases in areas such as patient information in medical research."

https://neo4j.com/whats-new-in-neo4j 
@musicog

**Comment by baukef** [comment]
It think this is solved with Solid Pods and Minio storage, see deliverable D5.3

**Comment by alastair** [comment]
Yes, agreed. Solid solved most of the concerns that we raised with this ticket.
